name: Update schema

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *

jobs:
  update-bindings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: 0.101.0

      - name: Update bindings
        run: nu scripts/update-bindings.nu

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(inputs): update bindings"
